from datetime import datetime
import requests
import json
import random

pms_desc = ["CARRY OUT - INSPECTION BY SERVICE ENGINEER", "CHECK - GENERAL PARTS", "CHECK & CLEAN - SEPARATOR CHAMBER / FILTER", "CLEAN & CALBIRATION - 15 PPM ALARM MONITORING EQUIPMENT"]
material_desc = [
    "FUSE\n",
    "OVERCURRENT RELAY\n",
    "TRANSFORMER\n",
    "FUSE\n",
    "AUX RELAY\n",
    "PILOT LAMP\n",
    "PUSH BUTTON SWITCH\n",
    "SELECTOR SWITCH\n",
    "TIMER RELAY\n",
    "VARIO SWITCH\n",
    "MAGNETIC CONTACTOR\n",
    "FUSE ELEMENT\n",
    "FUSE ELEMENT\n",
    "AUX RELAY\n",
    "PILOT LAMP\n",
    "PUSH BUTTON\n",
    "SELECTOR SWITCH\n",
    "FUSE FOR O.L.D\n",
    "BODY\n",
    "LIFITING LUG\n",
    "NAME PLATE\n",
    "HAND HOLE\n",
    "PRESSURE GAUGE\n",
    "NIPPLE FOR SAMPLING COCK\n",
    "THERMOMETER\n",
    "ELECTRIC HEATER\n",
    "TEMPERATURE SENSOR\n",
    "PALLRING BAG\n",
    "URETHANE MAT\n",
    "COALESCER FILTER(P.S.U.)\n",
    "BILGE INLET\n",
    "COALESCER FILTER(E.T.U.)\n",
    "PACKING(E.T.U.)\n",
    "HANDHOLE PACKING\n",
    "OIL INLET\n",
    "AIR VENT\n",
    "AUTO AIR VENT\n",
    "DRAIN OUTLET\n",
    "CLEAN WATER OUTLET\n",
    "SAFETY VALVE\n",
    "OIL LEVEL DETECTOR\n",
    "PACKING(P.S.U.)\n",
    "PRE-SEPARATOR UNIT(PSU)\n",
    "PRESS.GAUGE\n",
    "PRESS-GAUGE FOR BACKWASHING WATER\n",
    "AUTO AIR VENT VALVE\n",
    "ELEC.HEATER\n",
    "TEMP.SENSOR\n",
    "PRESSURE SWITCH\n",
    "EMULSION TREAT. UNIT(ETU)\n",
    "FOUNDATION\n",
    "CONTROL PANEL\n",
    "HEAT CONTROL PANEL\n",
    "SOLENOID V/V BOX\n",
    "BILGE ALARM UNIT\n",
    "OIL LEVEL DETECTOR\n",
    "THERMOMETER\n",
    "BILGE INLET (FROM O.BILGE PUMP)(5K-50A)\n",
    "BACKWASHING INLET (F.W)(5K-25A)\n",
    "AIR INLET (AIR VALVE CONTROL)\n",
    "TO OVERBOARD(BELOW 15PPM)(5K-40A)\n",
    "RE-CIRCULATION(ABOVE 15PPM)(5K-40A)\n",
    "OIL OUTLET(SEPARATED OIL DISC)(5K-25A)\n",
    "DRAIN OUTLET (5K-25A)\n",
    "SKID COAMING DRAIN OUTLET (5K-40A)\n",
    "BILGE INLET (NOT-RETURN V/V)\n",
    "ETU BACKWASHING IN (NON-RETURN V/V)\n",
    "PSU DRAIN (GLOBE V/V)\n",
    "ETU DRAIN (GLOBE V/V)\n",
    "PSU SAFETY VALVE\n",
    "ETU SAFETY VALVE\n",
    "OIL DISCHARGE (2-WAY AIR CYLINDER V/V)\n",
    "BACKWASHING (3-WAY)\n",
    "BY-PASS (3WAY)\n",
    "OVERBOARD/RE-CIR'N (3-WAY CYLINDER V/V)\n",
    "PRESS.REGULATING (PRESS.REGULATING V/V)\n",
    "BACKWASHING INLET (PRESS.REDUCING V/V)\n",
    "PSU BACKWASHING IN (NON-RETURN V/V)\n",
    "ETU IN/OUT (NON-RETURN V/V)\n",
    "GLOBE & GLOBE CHECK VALVE\n",
    "BODY\n",
    "HEXAGON NUT\n",
    "SPLIT PIN\n",
    "LOCK PLATE\n",
    "DISC LOCK WASHER\n",
    "PACKING\n",
    "NAME PLATE\n",
    "BONNET\n",
    "DISC\n",
    "VALVE DISC NUT\n",
    "PACKING GLAND\n",
    "GLAND NUT\n",
    "STEM\n",
    "SET SCREW\n",
    "HAND WHEEL\n",
    "SHEET PACKING (P.S.U)\n",
    "SHEET PACKING (E.T.U)\n",
    "HANDHOLE PACKING\n",
    "COALESCER FILTER (P.S.U)\n",
    "COALESCER FILTER (E.T.U)\n",
    "SPARE BOX\n",
    "ELECTRIC HEATER\n",
    "2WAY CYLINDER VALVE FOR OIL DISCHARGE\n",
    "BODY\n",
    "STEM\n",
    "PACKING SPRING\n",
    "SEAT RING\n",
    "PACKING\n",
    "O-RING\n",
    "GLAND BUSH\n",
    "SPRING\n",
    "SPRING SEAT\n",
    "PISTON\n",
    "ADJUST SCREW\n",
    "BOTTOM COVER\n",
    "HANDLE WHEEL\n",
    "HEX BOLT\n",
    "HEX BOLT\n",
    "HEX BOLT\n",
    "DISC LOCK NUT\n",
    "NUT\n",
    "LOCK NUT\n",
    "SPRING WASHER\n",
    "NUT\n",
    "PISTON RING\n",
    "YOKE\n",
    "O-RING\n",
    "O-RING\n",
    "O-RING\n",
    "O-RING\n",
    "O-RING\n",
    "O-RING\n",
    "NAME PLATE/SCALE\n",
    "HANDLE SCALE\n",
    "PISTON COVER\n",
    "TOP SEAT\n",
    "DISC\n",
    "DISC HOLDER\n",
    "DISC GUIDE\n",
    "3-WAY PISTON VALVE FOR AUTOMATIC STOPPING DEVICE\n",
    "BODY\n",
    "STEM\n",
    "PACKING SPRING\n",
    "SEAT RING\n",
    "PACKING\n",
    "GASKET\n",
    "GLAND BUSH\n",
    "SPRING\n",
    "SPRING SEAT\n",
    "PISTON\n",
    "BOTTOM FLANGE\n",
    "NAME PLATE/SCALE\n",
    "HEX BOLT\n",
    "HEX BOLT\n",
    "HEX BOLT\n",
    "DISC LOCK NUT\n",
    "NUT\n",
    "PISTON RING\n",
    "O-RING\n",
    "O-RING\n",
    "YOKE\n",
    "O-RING\n",
    "O-RING\n",
    "O-RING\n",
    "PISTON COVER\n",
    "TOP SEAT\n",
    "BOTTOM SEAT\n",
    "DISC\n",
    "DISC HOLDER\n",
    "DISC GUIDE\n",
    "3-WAY CYLINDER VALVE FOR BACKWASHING & BY-PASS\n",
    "BODY\n",
    "STEM\n",
    "PACKING SPRING\n",
    "SEAT RING\n",
    "PACKING\n",
    "GASKET\n",
    "GLAND BUSH\n",
    "SPRING\n",
    "SPRING SEAT\n",
    "PISTON\n",
    "ADJUST SCREW\n",
    "BOTTOM COVER\n",
    "HANDLE WHEEL\n",
    "HEX BOLT\n",
    "HEX BOLT\n",
    "HEX BOLT\n",
    "DISC LOCK NUT\n",
    "NUT\n",
    "LOCK NUT\n",
    "SPRING WASHER\n",
    "NUT\n",
    "PISTON RING\n",
    "YOKE\n",
    "O-RING\n",
    "O-RING\n",
    "O-RING\n",
    "O-RING\n",
    "O-RING\n",
    "O-RING\n",
    "NAME PLATE/SCALE\n",
    "HANDLE SCALE\n",
    "PISTON COVER\n",
    "TOP SEAT\n",
    "BOTTOM SEAT\n",
    "DISC\n",
    "DISC HOLDER\n",
    "DISC GUIDE\n",
    "PRESSURE REDUCING VALVE\n",
    "BODY\n",
    "SPRING CASE\n",
    "CAP\n",
    "SEAT\n",
    "DISC\n",
    "DISC HOLDER\n",
    "STEM\n",
    "DISC WASHER\n",
    "DISC LOCK NUT\n",
    "STEM GUIDE\n",
    "O-RING\n",
    "GUIDE LINER\n",
    "O-RING\n",
    "O-RING\n",
    "DIAPHRAGM\n",
    "B.SPRING SEAT\n",
    "STEM LOCK NUT/W\n",
    "ADJUST SPRING\n",
    "TOP SPRING SEAT\n",
    "HEX BOLT/S.W\n",
    "ADJUST SCREW\n",
    "LOCK NUT\n",
    "PLUG\n",
    "O-RING\n",
    "NAME PLATE\n",
    "CONNECTOR\n",
    "AIR PIN\n",
    "VENT PLUG\n",
    "OIL LEVEL DETECTOR\n",
    "CASE COVER\n",
    "FUSE\n",
    "TERMINAL\n",
    "CABLE GLAND\n",
    "GLAND CASE\n",
    "CONTROL PROBE ROD\n",
    "PILOT LAMP\n",
    "ADJUSTING DIAL\n",
    "TRIMMER\n",
    "TIMER SCREW\n",
    "MANUAL PUSH BUTTON\n",
    "AIR FILTER WITH PRESS. REGULATOR\n",
    "PRIMARY Pr.REGULATING VALVE\n",
    "BODY\n",
    "STEM GUIDE\n",
    "GASKET\n",
    "PLUG\n",
    "SPRING\n",
    "DIAPHRAGM\n",
    "LOWER SPRING SEAT\n",
    "UPPER SPRING SEAT\n",
    "LOCK NUT\n",
    "LOCK NUT\n",
    "BOLT\n",
    "BONNET\n",
    "ADJUST SCREW\n",
    "NUT\n",
    "O-RING\n",
    "O-RING\n"
]

url = "http://127.0.0.1:8000/pms/create_job"
headers = {
    'accept': 'application/json',
    'Content-Type': 'application/json'
}


def spare_parts(n):
    spare_parts = list()
    for i in range(n):
        spare_parts.append({"material_desc": random.choice(material_desc), "req_quantity": random.randint(5, 10), "existing_quantity": 0})
    return spare_parts


def populate_jobs():
    data = {
        "mach": "OILY WATER SEPARATOR(C)",
        "pms_desc": random.choice(pms_desc),
        "due": datetime.timestamp(datetime.now()) + 10000,
        "spare_parts": {"products": spare_parts(random.randint(5, 10))}
    }

    response = requests.post(url=url, headers=headers, data=json.dumps(data))
    print(response.content)


for i in range(30):
    populate_jobs()

